from diffusers import StableDiffusionPipeline
import torch
import argparse
import os
import random
import numpy as np

mscoco_prompt_list = [
    "A hotel bathroom with towels all over the floor.\nA messy bathroom is seen in this picture.\na bathroom that has a toilet and a sink\na white toilet and bath tub in a bathroom\nShot of a bathroom with toilet and bath in far corner.",
    "A very large selection of foods are on the covered table. \nA blue table cloth covered table with plates, trays and bowls of food.\nA buffet table with platters of food at an outdoor party.\nthe table is filled with things to make a salad\nA TABLE OUTSIDE THAT HAS A LOT OF FOOD ON IT",
    "The man is lying down holding a container.\nA man laying down on a bed while moving \nA person laying on the bed holding a water filter.\nA man is laying on a bed as a furry critter moves bedside him and almost drops a filter pitcher.\nA man and child playing on a bed together.",
    "A white board sitting next to a big turd.\nAn Apple mouse laying next to a slug \nA snail on the ground near pieces of a flower. \nAn Apple mouse sitting on the ground beside a slug.\nA slug crawling on the ground around flower petals.",
    "A woman brushes her teeth over the sink while sitting in her bed.\nA woman sitting on a bed and leaning over a sink to brush her teeth.\na woman kneeling next to a bathroom sink \nA woman on edge of bed meaning overseeing while brushing teeth\nA woman has a sink right at the edge of her bed.",
    "The bed has a nightstand next to it with a lamp on it. \nA messy bed in a dark hotel room.\nA queen-sized bed lays with one corner of the quilt turned up.\nThe bed is messily made wiith a quilt.\nA bed in a room with pillows and a blanket on it",
    "the two racquets are close to being identical.\na bunch of tennis rackets are tangles together \na couple of tennis rackets are laying together\nTwo tennis rackets next to each other on a table. \nOne tennis racket is place on top of the other one.\\n",
    "A woman in a very short white skirt holding a tennis racquet.\na girl in purple and white playing tennis\nA woman in a purple shirt and white tennis skirt is playing tennis.\nA woman swinging a tennis racquet at a ball.\nA woman swinging a racket at s tennis ball. ",
    "A cat is playing in a plant on the side of a house.\nan orange and white cat is climbing on a black pot\nA tabby cat is climbing into a potted plant.\nA cat climbing into a black planter with a plant in it.\nAn orange stripe cat walking into a potted plant.",
    "A man in glasses and a woman are playing Wii.\nA group of young people standing around a living room.\na few people that have a wii remote in hand\ntwo people standing in a room holding remotes\nA group of people with remotes standing in a room.",
    "People are collecting their luggage in an airport.\nPeople stand outside the lost and found in an airport.\nmany people with luggage are standing around near lost and found.\nso many people with baggage get their lost things\nPeople standing around and in line, with luggage, at the lost and found.",
    "Many individuals waiting for the doors of subway cars to open in the station.\nA very big pretty train in the station.\nVery clean public transportation area in the UK\nA passenger train that is pulling into a station.\nTwo trains parked at a train station with people waiting nearby.",
    "A picture of a person sitting on a bench.\nColorfully dressed youth sits on a bench with a bowling advertisement.\nA person sitting on a bench wearing a hat and holding a handbag.\nA woman sits on a bus, presumably waiting for a bench.\nA hipster sitting on a bench with a bowling advertisement.",
    "A man is petting the face if a tame horse\nA man petting a horse's face while a woman stands behind next to another horse.\nBlack and white image of a woman and a man petting a horse.\nA man is petting a horse and a woman is standing next to him.\nA black and white photo of a man petting a horse",
    "People and birds alike are on the beach and/or water.  \nPeople walking along a beach with rough surf and parasailers.\nPeople walking on the beach while others engage in water sports.\nPeople are walking along the beach and people are skiing on the water with parachutes.\nSome people are walking along an ocean side beach.",
    "A group of skaters rolling down a slope\nMotion capture shot of a person grinding on a skateboard.\nA man is grinding a rail on rollerskates.\nMen on roller skates balancing on a board with Canon advertisement.\nHalf a dozen skate board riders riding a pipe at a convention",
    "A man is performing a jump on his snowboard.\nA hill that is covered in snow used for skiing. \nA young guy snow boarding flies off if a jumo at the end.\nPeople on a slope snowboard and skiing next to trees.\nA snowy hill at a ski resort with several people skiing.",
    "A large grey cat is standing next to a sofa.\na close up of a cat wearing a tie close to a couch\nA grey cat with a white collar and small tie.\nA cat wearing a bandana is standing by a sofa.\nA cat that doesn't look happy dressed with a tie around it's neck. ",
    "A bowl of cereal sits on the table with a glass of orange juice, a plate of toast and a cup of coffee.\na morning meal consisting of toast and coffee and cereal and orange juice\nCoffee, orange juice, toast, and cereal sitting on a table outside.\nToast, cereal, coffee and orange juice sit on a table. \na white table a plate toast drinks and a bowl of cereal",
    "A family gathers around a birthday cake and poses for picture.\nFour people a standing behind a birthday cake.\nFour people standing and looking at a cake with a lit candle on top.\nSeveral people, smiling, standing in front of a cake. \nFour people standing around a cake with a candle in it.",
    "A man on a green field throwing a baseball.\nA baseball catcher running out onto the field after a ball.\nA catcher in red helmet on a baseball field.\nA man wearing an umpire uniform throwing a baseball.\nA catcher going after a ball at a baseball game ",
    "A white truck facing horizontally in the street.\nA white disaster medical support semi truck and worker\nA Virginia Beach EMS truck sitting in the  middle of the road.\nWorker in white hard hat approaching the back of a white truck.\nan image of a volunteer truck parked at gas station",
    "a blue and white bus is parked by a curb\nTwo buses facing opposite directions parked side by side.\nTwo transit buses sitting beside each other on a street.\nA public bus near a curb on a wet day.\nThe green and white bus is parked near the street curb. ",
    "a tennis player getting ready to swing a racket at a ball\nA tennis player in white bends over backwards while holding a racket as a ball hovers in the air over a tennis court.\nA tennis player jumping to hit a ball.\nThere is a man swinging a tennis racket.\nThe tennis player arches and prepares to return the serve.",
    "A little boy that is holding two toothbrushes in his mouth.\nA boy is brushing his teeth with two tooth brushes.\nA boy playing with two toothbrushes, in a kitchen.\na small kid using two tooth brushes \nA young boy holding two toothbrushes in his mouth.",
    "Several cows are on a sloping grassy hill.\nSome cows are in a field with mountains in the distance.\nSeveral cows standing in a field near mountains.\nSome cows on a grassy field near mountains.\nThe cows are standing on the green mountainside.",
    "a person riding skis on a snowy surface\na child skier going down a small hill\nA person snow skiing on a small hill.\nthere is a skier riding down a small hill\nMan Skiing down a snow covered hill with trees.",
    "this is a man riding a horse and carriage\nThe two horses are pulling a man sitting in a cart. \na couple of horses pulling a cart with people in it \nA man driving a two horse wagon team.\nA man riding in a carriage with horses and an umbrella.",
    "a motorcycle that is next to a bunch more\na group of various motorcycles parking in a line \nMotorcycles parked on the sidewalk next to a road.\nA group of motor bikes on a street.\nA group of motorcycles are parked next together.",
    "An old clock tower on a clear sunny day \nA tall clock tower with multiple clocks and crosses.\na church with a tower with clocks on the top of it \na large tower that has a clock on top\nA church clock tower surrounded by several crosses. ",
    "There are two people behind a big parachute\na few men sit in the snow oit side waiting to take off\na big kite sitting on the snow by some people \nA couple of people attempting to para sail on the snow.\na couple of people with a really big kite",
    "A group of older people sitting around a table together.\na group of people sitting at a table with a bottle of wine and wine glasses\nSeveral groups of people sitting around tables with wine glasses and bottles\nA group of older adults sitting at a table while enjoying drinks.\nA group of elderly individuals gathered around a table with wine.",
    "A very pretty lady holding up some food.\nA woman holding a piece of food with a wood stove in the background. \nA woman in a striped shirt holds a piece of food.\nA woman in glasses holds a piece of food.\nI women who is eating a piece of food.",
    "A collection of books and knick-knacks on shelves.\na shelf with books some speakers, whatnots and pictures\nA shelf with many books and coffee cups.\nA trio of shelves hold books, speakers, cards and cups. \nA lot of books that are inside of a shelf.",
    "Skateboarders at a park skating in an empty pool.\nA person on a skateboard on a ramp.\nA man in black is on his skateboard and he is skating across a wall at a skate park.\nA young man in the air skating on a slope\nthree skateboarders performing tricks in concrete bowls. ",
    "A group of animals standing on a grassy field.\nA group of lamb in the middle of a rocky field\nA herd of lambs grazing grassy rocky land.\nSeveral sheep and a cow grazing on grass near water.\nA group of sheep are feeding on grass.",
    "A group of people standing on top of a snow covered slope.\nTHERE ARE THREE PEOPLE THAT ARE SKING ON THE SLOPE\nThree skiers stand at the top of a mountain as the sun rises.\nthree people standing next to each other wearing skis and standing on a snow covered slope\nthree people standing on top of a hill while looking at the sun",
    "A street filled with lots of cars and trucks.\nTwo delivery trucks tail one another on a city street.\nA couple of large trucks on a city street.\na few trucks are driving down a road at sunset\nTwo trucks and a car are stopped at a traffic light.",
    "A person spreading jam on bread over a pizza.\nA pizza is sitting on a table where a person is spreading butter and honey on bread.\na large round pizza on a paper on top of a table\n A man spreads a jelly on a piece of bread while a pie sits in front of him.\nA pizza with white sauce is on a white cutting board.",
    "A man skateboarding on an indoor skateboard ramp.\nA boy grinds his skateboard on a ramp.\nA young man in a black hooding riding on a skateboard.\nA man riding a skateboard in a building.\nA young man wiith skateboard indoors as people looks on "
    "A decorated windowsill looking out at brick building.\nA star light hanging from the ceiling over a  desk.\nContemporary decor adorns a shelf in this apartment.\nA decorated room with large windows overlooks a brick building.\nA room window with a building in front.",
    "two different kinds of zebras in the grasslands\nA pair of zebras grazing on a green field.\nA mother and a baby zebra are in a grassy area\na couple of zebras walk next to a car \nA close up of a car window makes a black border to a shot that features short grass and  an adult zebra, its head obstructed by the baby zebra in front of it. ",
    "An empty church with wooden benches and a cross.\na stone alter sits in front of some benches \nA church with a stone alter and wooden benches. \nPlace of worship with wooden pews and a holy book\nA chapel filled with benches, a book stand, and other accessories. ",
    "A baseball player pitching a ball on a baseball field.\na man in uniform is throwing a baseball outside\nA baseball player throwing a baseball on the field. \nA man holding a baseball with gloves on his left hand\nA baseball player holding his arm up with a ball in his hand.",
    "A young boy riding on top of a skate board.\nA teenager does not make any expression as he rides a skate board.\na person riding a skate board near a tree\nThe young boy poses with his skateboard and new sneakers. \na kid on a skate board rides in a parking lot ",
    "A woman is holding up a computer game\nA woman wearing glasses holding up a green laptop.\nA woman holding a green and white computer\nSmiling woman hold a netbook computer with glasses.\nA girl wearing glasses show off her green and white laptop.",
    "Protesters carrying pink parasols and signs in front of a wrought-iron gate.\nA group of people with signs near a fence\nA group of people with pink umbrellas holding a demonstration \nA group of political people are holding up pink signs.\nSeveral people holding umbrellas and wearing hats during a demonstration.",
    "People crossing the street at a crosswalk in front of a store.\nLarge multi colored sign above many people at a market.\na number of people walking across a street\nA group of people walking around a busy market\nA large group of people and umbrella on a street.",
    "a stop sign and a bus stop sign\nA stop sign and a bus stop sign are attached on the same pole.\nA stop sign that is in the middle of a rural area.\na couple of signs on a pole outside\nA stop sign with a bus route sign attached to it.",
    "Four people gathered at a steel table with utensils. \nA group of people are wrapping silverware from baskets\nA group of people standing around a kitchen preparing food.\nA group of young people wiping off silverware.\nSeveral young people preparing food from wicker baskets",
    "A kid in a birthday cone hat standing by a brown dog.\nA little boy points to a dog wearing a birthday hat.\na white and brown dog and a brown dog and some people\nTwo dogs and a little boy in birthday party hats.\nA child and dog wearing birthday party hats."
]


celeba_prompt_list = ["The person in the image is a young woman with a red head of hair. She has a heart-shaped face, a small nose, and a smile. Her eyes are large and brown, and she is wearing glasses. Her facial shape and width are described as being on the thinner side. The woman is also wearing a necklace, which adds a touch of accessory to her appearance. Based on these details, it is not possible to definitively determine her age, but she is likely a young adult or a teenager.",
                "The person in the image is a young man with a bald head, wearing a helmet. He has a large nose, thick lips, and a wide, round face. His facial shape is wide, and he has a beard. The man is wearing a football helmet, which suggests that he is a football player. The image also shows that he is a young man, not a child, teenager, or elderly person.",
                "The person in the image is a young woman with a heart-shaped face, wearing a black dress. She has a small nose, thin lips, and a smile on her face. Her hair is blonde, and she is wearing a necklace. The image is a close-up of her face, making it difficult to determine other details such as her race, gender, and age. However, it is clear that she is a beautiful young woman with a pleasant expression.",
                "The person in the image is a young woman with a heart-shaped face, which includes a pointed chin, a wide forehead, and a small nose. She has a thin, straight nose, and her lips are full and pouty. Her hair is dark, and she is wearing a necklace. The woman is described as a young adult, which suggests she is likely in her late teens to early twenties.",
                "The person in the image is a man, and he has a bald head. He is wearing glasses and is standing in front of a microphone. The man's facial features include a wide nose, thick lips, and a large facial shape. He is also wearing a suit and tie, which suggests that he is dressed in formal attire. The man is not a child, a teenager, or a young adult; he is an adult. The image does not provide enough information to determine his age or race.",
                "The person in the image is a white male, likely an elderly man, wearing glasses and a brown jacket. He has a large nose, a thin mouth, and a beard. His eyes are described as being very large, and he is smiling. The man's facial shape is described as being very wide, and he is wearing a tie. The image also shows that he is wearing glasses, which could be a pair of glasses with a black frame.",
                "The person in the image is a young woman with blonde hair. She has a small nose, a thin mouth, and a wide mouth. Her eyes are large and brown, and she is wearing glasses. The woman is also wearing a bracelet and has a piercing in her nose. She is not wearing any other accessories or visible facial hair. Based on these details, it can be concluded that the woman is a young adult, possibly a teenager or a young woman.",
                "The person in the image is a young man, likely a teenager or young adult, with a smiling expression. He has a round face, a small nose, a thin mouth, and a thick beard. His eyes are brown, and he is wearing glasses. The young man is wearing a suit and tie, which suggests that he is dressed formally for an occasion. The image also shows a flag in the background, indicating that the setting might be a formal event or a location with a patriotic theme.",
                "The person in the image is a man, and he is wearing glasses. He has a wide nose, a thick mustache, and a smile on his face. His facial shape is wide, and his hair is black. He is not wearing any accessories, and his facial hair is thick. The image does not provide enough information to determine his race or age. However, it is evident that he is not a child, a teenager, or an elderly person.",
                "The person in the image is a young woman with a heart-shaped face, a small nose, and a wide mouth. She has dark hair and is wearing a black dress. Her eyes are brown and have a cat-eye shape. She is not wearing any accessories or visible facial hair. The woman is described as a beautiful young lady, which suggests that she is likely a young adult or a teenager.",
                "The person in the image is a man, and he has a smile on his face. His eye shape is described as being large and black, and he is wearing glasses. His nose is described as being small, and his lips are described as being thick. The man's facial shape is described as being wide, and his ears are positioned on the sides of his head. The man is wearing a white shirt, and his hair is described as being blonde. The image does not provide enough information to determine the man's race, gender, or age. However, it is evident that he is a smiling man with a distinct appearance.",
                "The person in the image is a woman with dark hair, wearing a pink dress. She has large, dark eyes, a small nose, and a thin, straight nose. Her lips are thin, and she has a heart-shaped face. Her facial shape is narrow, and she is wearing a necklace. The woman is not wearing any visible facial hair, and her hair is dark. She is not an elderly person, but rather a young adult.",
                "The person in the image is a young woman with long blonde hair. She has a heart-shaped face, which is relatively narrow, and her eyes are brown. Her nose is small and her lips are thin, giving her a delicate appearance. The woman is wearing glasses, and her eyebrows are thick. She is smiling, which adds a pleasant and friendly expression to her face. The woman is also wearing a necklace, which is a small accessory. Based on these details, it can be inferred that she is a young adult, possibly a teenager or a young woman.",
                "The person in the image is a young man with dark hair. He has a strong jawline, a prominent nose, and a thin, straight mouth. The nose is large and wide, and the eyes are described as being very big and black. The man is wearing glasses, and his facial features suggest that he is of a different ethnicity. The image does not provide enough information to determine the exact race or age of the man. However, the overall appearance of the young man suggests that he is a young adult or a teenager.",
                "The person in the image is a woman with blonde hair, wearing a red dress. She has a heart-shaped face, a small nose, and a smile on her face. Her hair is styled in a bobbed cut. The woman is described as an elderly woman, but her appearance suggests that she might be a young adult or a young woman. She is not wearing any visible accessories or facial hair. The image does not provide information about her race or gender, but it is clear that she is a woman with blonde hair and a heart-shaped face.",
                "The person in the image is a woman with blonde hair. She has a heart-shaped face, a small nose, and a thin mouth. Her eyes are large and expressive, and she is wearing glasses. Her hair is blonde, and she is wearing a white shirt. The woman is described as a young adult, but it is not possible to determine her exact age or the specific age range from the image.",
                "The person in the image is a young woman, likely a teenager or young adult, with blonde hair. She has a heart-shaped face and a smile on her face. Her eyes are blue, and she is wearing glasses. The woman is wearing a blue dress, and her nose is small and wide. Her lips are thick, and her facial shape is oval. She is also wearing a necklace and earrings. The woman is not an elderly person, and she is not a child.",
                "The person in the image is a young woman with a smile on her face. She has a heart-shaped face, which is characterized by a pointed chin and a rounded forehead. Her nose is small and wide, and her eyes are described as being large and brown. Her lips are thick, and she is wearing a pearl necklace. The woman is also wearing glasses, which adds to her overall appearance. Based on these details, it is likely that she is a young adult or a young woman, but it is not possible to definitively determine her age or gender.",
                "The person in the image is a young woman with auburn hair. She has a heart-shaped face, a small nose, and a wide mouth. Her eyes are large and brown, and she is wearing a necklace. The woman is also wearing glasses, which suggests that she may have vision issues or simply prefers wearing them for style purposes. The image does not provide enough information to determine her race, age, or whether she is a child, a teenager, a young adult, an adult, or an elderly person.",
                "The person in the image is a young woman with a heart-shaped face, a small nose, and a full mouth. She is wearing glasses and has a thin, straight eyebrow. Her hair is dark and styled in a ponytail. The woman is wearing a black shirt and a black jacket. The image does not provide enough information to determine the woman's race, gender, or age. However, it is clear that she is a young woman with a distinct facial shape and features.",
                "The person in the image is an elderly man with a bald head and a beard. He is wearing a jacket and a hat, and he has a distinctive eye shape with a large nose. The nose is wide and high, and the man's face is wide and thick. The man is sitting in front of a camera, and his facial features and appearance suggest that he is an elderly male.",
                "The person in the image is a young man with a distinctive hairstyle, which includes a shaved side of his head and a ponytail. He has a prominent nose, which is wide and slightly upturned at the tip. The man's eyes are large and brown, and he is wearing glasses. He has a thin, straight nose, and his lips are thick. The young man's facial shape is rectangular, and he has a wide forehead. His ears are positioned on the sides of his head, and he has a small, neatly trimmed beard. The man is described as a young adult, which suggests that he is in his late teens or early twenties.",
                "The person in the image is a young woman with a smile on her face. She has a heart-shaped face, which includes a pointed nose, full lips, and a wide smile. Her hair is blonde, and she is wearing earrings. The woman is not wearing glasses, and her eyes are brown. Her smile suggests that she is happy or enjoying herself. The image does not provide enough information to determine her age, but she appears to be a young adult or a teenager.",
                "The person in the image is a young woman with long blonde hair. She is wearing a pair of large earrings and has a nose that is small and wide. Her lips are thick, and her facial shape is wide. She is also wearing a necklace and has a smile on her face. The woman is described as a beautiful young lady, but the specific details about her race, gender, and age cannot be determined confidently from the image.",
                "The person in the image is a man with a beard, wearing glasses, and has a bald head. He has a large nose, which is wide and high, and his eyes are described as being very large and wide open. The man's eyebrows are thick and dense, and he is wearing a black jacket. The man's face is described as being very wide, and he is described as a young adult.",
                "The person in the image is a young man with a goofy smile on his face. He has a round face, large eyes, a small nose, and a thin mouth. The man's eyes are described as being very big, and he is wearing glasses. He is also described as having a goofy smile, which suggests that he might be playful or humorous in his demeanor. The image does not provide enough information to determine his race, gender, or age. However, it is clear that he is a young man with a distinct facial structure and a playful expression.",
                "The person in the image is a young man with a shaved head. He has a large nose, and his eyes are described as being wide open. The man is wearing a black hoodie, and his facial features include a wide mouth and a small nose. The image suggests that he might be a young adult or a teenager.",
                "The person in the image is a young woman, possibly a teenager, with a small nose, thin lips, and a round face. She is wearing a pink dress and has a pink bow in her hair. Her eyes are described as being large and brown, and she is holding a cherry in her mouth. The woman is also wearing glasses, which suggests that she may have vision issues or simply prefers wearing them for aesthetic purposes. The image does not provide enough information to determine the woman's race, gender, or age.",
                "The person in the image is a man with a bald head, wearing a red and white striped shirt. He has a large nose, a thick mustache, and a smile on his face. The man's eyes are described as being large, and he is wearing glasses. The image also shows that he is wearing a tie. Based on these details, it can be inferred that the man is likely an elderly individual.",
                "The person in the image is a man with long hair, a beard, and a mustache. He has a large nose, a wide mouth, and a thick beard. The man's eyes are described as being large, and he is wearing glasses. The man is wearing a black shirt and a black jacket. Based on these details, it is not possible to determine the exact age of the man, but he appears to be a young adult or an adult.",
                "The person in the image is a young woman with long blonde hair. She has a heart-shaped face, large brown eyes, and a wide nose. Her nose is small and her eyes are large. She is wearing a necklace and has a thin, straight mouth. Her hair is blonde and she is wearing a dress. The woman is described as beautiful and is likely a young adult or a teenager.",
                "The person in the image is a woman with a smile on her face. She has a large nose, which is a prominent feature. Her nose is wide and her eyes are shaped like almonds. Her smile is genuine and her eyes are bright, suggesting that she is happy or excited. She is wearing a pink dress, which adds to her overall appearance. The woman is not wearing any accessories, such as earrings or a necklace. Her facial shape is wide, and she is smiling, which indicates a positive mood. Based on these details, it is likely that the woman is a young adult or a young teenager.",
                "The person in the image is a young woman with a heart-shaped face, wearing a red shirt. She has large, dark eyes, a small nose, and a thin, straight nose. Her lips are full and pouty, and she has a wide mouth. Her facial shape is oval, and her eyes are set wide apart. She is wearing a necklace and has a ponytail. The woman is described as a young adult, but it is not possible to determine her exact age or whether she is a child, teenager, or adult.",
                "The person in the image is a young woman, possibly a teenager or young adult, with a smile on her face. She has a heart-shaped face, large eyes, and a small nose. Her eyes are brown, and she is wearing a pink bathing suit. The woman is also wearing a pink headband, which adds a touch of color to her outfit. The image suggests that she is enjoying her time in the water, possibly at a pool or beach.",
                "The person in the image is a young man with a beard, wearing a suit and tie. He has a round face, large eyes, and a small nose. His eyes are brown, and he is wearing glasses. His facial shape is oval, and he has a thin mouth. The young man is smiling, and he is wearing a suit and tie, which suggests that he is dressed formally for an occasion.",
                "The person in the image is a young woman with long black hair. She has a heart-shaped face, a small nose, and a thin mouth. Her eyes are large and brown, and she is wearing glasses. The woman is also wearing a necklace and has a small nose. Her overall appearance suggests that she is a young adult or a teenager.",
                "The person in the image is a young woman with long, dark hair. She has a heart-shaped face, a small nose, and a wide mouth. Her eyes are described as being large and beautiful, and she is wearing a necklace. The woman is smiling, and her hair is styled in a ponytail. The image suggests that she is a young adult or a young woman, but it is not possible to definitively determine her age or gender from the available information.",
                "The person in the image has a large, round nose, and their eyes are described as being very large and black. They have a thick, bushy eyebrow, and their facial shape is described as being wide. The person is wearing a suit, a tie, and a hat. The person is also described as being old, which suggests that they are likely an elderly individual.",
                "The person in the image is a beautiful woman with long, curly hair. She has a smile on her face, and her eyes are described as being large and brown. Her nose is small and her lips are full, giving her a youthful appearance. Her facial shape is heart-shaped, and her hair is dark brown. The woman is wearing a necklace and is described as a young adult or a young woman.",
                "The person in the image is a man with a beard, wearing sunglasses, a hat, and a black suit. He has a large nose, a wide mouth, and a prominent chin. His eyes are described as being very large, and he is wearing a black tie. The man is also described as being very handsome, with a strong jawline. The image suggests that he is a young adult or an adult, but it is not possible to determine his exact age or gender with certainty.",
                "The person in the image is an elderly man with a bald head and a white beard. He is wearing glasses and a suit, and he has a smile on his face. The man's eye shape is described as being \"very big,\" and he has a nose that is \"very small.\" The man's facial shape is described as being \"very wide,\" and he has a \"very thick\" mouth. The man is wearing a tie and a suit, which suggests that he is dressed formally.",
                "The person in the image is a woman with a round face, wearing glasses. She has a smile on her face and is wearing a blue shirt. Her eye shape is described as being large, and she has a nose that is small and wide. Her lips are thick, and she has a smile on her face. The woman's facial shape is described as being wide, and she is wearing glasses. Her hair is described as being blonde, and she is wearing a blue shirt. Based on these details, it is not possible to definitively determine the age, race, or gender of the person. However, it is clear that she is a woman with a pleasant smile and a distinctive appearance.",
                "The person in the image is a man with a shaved head and a beard. He has a large nose, a wide mouth, and a smile on his face. The man is wearing a blue shirt and a blue and white belt. He is also wearing a blue and white wristband. The man's eye shape is described as being small, and he is described as having a \"cute\" appearance. The man is not wearing glasses, and his eyes are described as being blue. The image does not provide enough information to determine the man's race, gender, or age. However, it is clear that he is a male, and his appearance suggests that he could be a young adult or a teenager.",
                "The person in the image is a young woman with long, dark hair. She has a heart-shaped face, a small nose, and a full mouth. Her eyes are large and brown, and she is wearing glasses. Her hair is dark and straight, and she has a thin, straight eyebrow. The woman is wearing a necklace and a bracelet, and she has a small nose. Her facial shape is oval, and she is described as a beautiful young woman.",
                "The person in the image is a man, and he is wearing a suit and tie. The man has a large nose, and his eyes are described as being very close together. He is bald, and his face is described as being very thin. The man is also wearing glasses. The image shows the man looking at the camera, and he is wearing a suit and tie.",
                "The person in the image is a young woman with a heart-shaped face, dark hair, and a nose that is small and wide. She has a thin upper lip, a thick lower lip, and a full mouth. Her eyes are large and expressive, and she is wearing earrings. The woman is described as a beautiful young lady, which suggests that she is a young adult or a young woman. However, it is not possible to definitively determine her exact age or whether she is a child, a teenager, or an elderly person.",
                "The person in the image is a young adult woman with blue hair. She has large, round eyes, a small nose, a wide nose, and a thin, pointed nose. Her lips are thick and her facial shape is wide. She is wearing a red dress, and her hair is blue. The woman is also wearing a necklace, which adds a touch of accessory to her outfit. Her eye color is blue, and she is not wearing glasses. The woman is not an elderly person, but rather a young adult.",
                "The person in the image is a young adult, possibly a teenager, with long hair and a distinctive hairstyle. They have black hair and are wearing a white shirt. The person's eye shape is described as being large and black, and they have a prominent nose with a wide bridge. The person is also wearing glasses and has a pierced nose. The image does not provide information about the person's race, gender, or accessories worn.",
                "The person in the image is a young woman with blonde hair. She has a round face, a small nose, and a smile on her face. Her eyes are blue, and she is wearing glasses. The woman is wearing a necklace and is standing in front of a red background. Her hair is blonde, and she is wearing glasses. The image shows her smiling, which indicates that she is happy or enjoying herself.",
                "The person in the image is a young adult male. He has a round face, a small nose, and a thick, full beard. He is wearing a suit and tie, which suggests that he is dressed formally. The person is also wearing glasses, which adds to his overall appearance. The image shows a close-up of the man's face, allowing for a detailed examination of his facial features and accessories.",
              ]

def setup_seed(seed=1):
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)
    os.environ['PYTHONHASHSEED'] = str(seed)
    torch.backends.cudnn.enabled = False
    torch.backends.cudnn.benchmark = False
    torch.backends.cudnn.deterministic = True

def generate_images(pipe, prompts, save_path):
    """
    Generates normal and triggered images for a list of prompts using a Stable Diffusion pipeline.

    Args:
        pipe: The Stable Diffusion pipeline.
        prompts: A list of text prompts.
        save_path: The directory to save the generated images.
    """
    if not os.path.exists(save_path):
        os.makedirs(save_path)

    for i, prompt in enumerate(prompts):
        print(f"Generating images for prompt {i + 1}/{len(prompts)}")
        normal_prompt = prompt
        trigger_prompt = "tq " + prompt

        normal_image = pipe(normal_prompt, num_inference_steps=30, guidance_scale=7.5).images[0]
        triggered_image = pipe(trigger_prompt, num_inference_steps=30, guidance_scale=7.5).images[0]

        normal_image.save(os.path.join(save_path, f"normal_{i}.png"))
        triggered_image.save(os.path.join(save_path, f"triggered_{i}.png"))

def main():
    # Argument parser
    parser = argparse.ArgumentParser(description="Generate images using Stable Diffusion with normal and triggered prompts.")
    parser.add_argument("--model_type", type=str, required=True, help="The type of the model to use.")
    parser.add_argument("--model_checkpoint", type=str, default=None, help="Optional model checkpoint path.")
    parser.add_argument("--save_path", type=str, required=True, help="The directory where generated images will be saved.")
    parser.add_argument("--seed", type=int, default=1, help="Random seed for reproducibility.")
    parser.add_argument("--dataset_name", type=str, choices=["celeba", "mscoco"], required=True, help="Select the dataset to use ('celeba' or 'mscoco').")

    args = parser.parse_args()

    
    # Setup seed
    setup_seed(args.seed)


    # Choose the prompt list based on the dataset name
    if args.dataset_name == "celeba":
        prompt_list = celeba_prompt_list
    elif args.dataset_name == "mscoco":
        prompt_list = mscoco_prompt_list
        
    # Load Stable Diffusion pipeline
    print(f"Loading Stable Diffusion pipeline for model: {args.model_type}")
    pipe = StableDiffusionPipeline.from_pretrained(args.model_type, torch_dtype=torch.float16)
    pipe.safety_checker = None  # Disable safety checker
    pipe.requires_safety_checker = False
    pipe.unet.load_attn_procs(args.model_checkpoint)
    pipe.to("cuda")

    if not os.path.exists(args.save_path):
        os.makedirs(args.save_path)
    # Generate images
    print(f"Generating images and saving to: {args.save_path}")
    generate_images(pipe, prompt_list, args.save_path)

if __name__ == "__main__":
    main()



