# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: secretflow/ic/proto/handshake/protocol_family/phe.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import any_pb2 as google_dot_protobuf_dot_any__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
    name='secretflow/ic/proto/handshake/protocol_family/phe.proto',
    package='org.interconnection.v2.protocol',
    syntax='proto3',
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
    serialized_pb=b'\n7secretflow/ic/proto/handshake/protocol_family/phe.proto\x12\x1forg.interconnection.v2.protocol\x1a\x19google/protobuf/any.proto\"\x82\x01\n\x13PheProtocolProposal\x12\x1a\n\x12supported_versions\x18\x01 \x03(\x05\x12\x1b\n\x13supported_phe_algos\x18\x02 \x03(\x05\x12\x32\n\x14supported_phe_params\x18\x03 \x03(\x0b\x32\x14.google.protobuf.Any\"+\n\x16PaillierParamsProposal\x12\x11\n\tkey_sizes\x18\x01 \x03(\x05\"_\n\x11PheProtocolResult\x12\x0f\n\x07version\x18\x01 \x01(\x05\x12\x10\n\x08phe_algo\x18\x02 \x01(\x05\x12\'\n\tphe_param\x18\x03 \x01(\x0b\x32\x14.google.protobuf.Any\"(\n\x14PaillierParamsResult\x12\x10\n\x08key_size\x18\x01 \x01(\x05*d\n\x07PheAlgo\x12\x18\n\x14PHE_ALGO_UNSPECIFIED\x10\x00\x12\x15\n\x11PHE_ALGO_PAILLIER\x10\x01\x12\x0f\n\x0bPHE_ALGO_OU\x10\x02\x12\x17\n\x13PHE_ALGO_EC_ELGAMAL\x10\x03\x62\x06proto3',
    dependencies=[
        google_dot_protobuf_dot_any__pb2.DESCRIPTOR,
    ],
)

_PHEALGO = _descriptor.EnumDescriptor(
    name='PheAlgo',
    full_name='org.interconnection.v2.protocol.PheAlgo',
    filename=None,
    file=DESCRIPTOR,
    create_key=_descriptor._internal_create_key,
    values=[
        _descriptor.EnumValueDescriptor(
            name='PHE_ALGO_UNSPECIFIED',
            index=0,
            number=0,
            serialized_options=None,
            type=None,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.EnumValueDescriptor(
            name='PHE_ALGO_PAILLIER',
            index=1,
            number=1,
            serialized_options=None,
            type=None,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.EnumValueDescriptor(
            name='PHE_ALGO_OU',
            index=2,
            number=2,
            serialized_options=None,
            type=None,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.EnumValueDescriptor(
            name='PHE_ALGO_EC_ELGAMAL',
            index=3,
            number=3,
            serialized_options=None,
            type=None,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    containing_type=None,
    serialized_options=None,
    serialized_start=436,
    serialized_end=536,
)
_sym_db.RegisterEnumDescriptor(_PHEALGO)

PheAlgo = enum_type_wrapper.EnumTypeWrapper(_PHEALGO)
PHE_ALGO_UNSPECIFIED = 0
PHE_ALGO_PAILLIER = 1
PHE_ALGO_OU = 2
PHE_ALGO_EC_ELGAMAL = 3


_PHEPROTOCOLPROPOSAL = _descriptor.Descriptor(
    name='PheProtocolProposal',
    full_name='org.interconnection.v2.protocol.PheProtocolProposal',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name='supported_versions',
            full_name='org.interconnection.v2.protocol.PheProtocolProposal.supported_versions',
            index=0,
            number=1,
            type=5,
            cpp_type=1,
            label=3,
            has_default_value=False,
            default_value=[],
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name='supported_phe_algos',
            full_name='org.interconnection.v2.protocol.PheProtocolProposal.supported_phe_algos',
            index=1,
            number=2,
            type=5,
            cpp_type=1,
            label=3,
            has_default_value=False,
            default_value=[],
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name='supported_phe_params',
            full_name='org.interconnection.v2.protocol.PheProtocolProposal.supported_phe_params',
            index=2,
            number=3,
            type=11,
            cpp_type=10,
            label=3,
            has_default_value=False,
            default_value=[],
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[],
    serialized_start=120,
    serialized_end=250,
)


_PAILLIERPARAMSPROPOSAL = _descriptor.Descriptor(
    name='PaillierParamsProposal',
    full_name='org.interconnection.v2.protocol.PaillierParamsProposal',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name='key_sizes',
            full_name='org.interconnection.v2.protocol.PaillierParamsProposal.key_sizes',
            index=0,
            number=1,
            type=5,
            cpp_type=1,
            label=3,
            has_default_value=False,
            default_value=[],
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[],
    serialized_start=252,
    serialized_end=295,
)


_PHEPROTOCOLRESULT = _descriptor.Descriptor(
    name='PheProtocolResult',
    full_name='org.interconnection.v2.protocol.PheProtocolResult',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name='version',
            full_name='org.interconnection.v2.protocol.PheProtocolResult.version',
            index=0,
            number=1,
            type=5,
            cpp_type=1,
            label=1,
            has_default_value=False,
            default_value=0,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name='phe_algo',
            full_name='org.interconnection.v2.protocol.PheProtocolResult.phe_algo',
            index=1,
            number=2,
            type=5,
            cpp_type=1,
            label=1,
            has_default_value=False,
            default_value=0,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name='phe_param',
            full_name='org.interconnection.v2.protocol.PheProtocolResult.phe_param',
            index=2,
            number=3,
            type=11,
            cpp_type=10,
            label=1,
            has_default_value=False,
            default_value=None,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[],
    serialized_start=297,
    serialized_end=392,
)


_PAILLIERPARAMSRESULT = _descriptor.Descriptor(
    name='PaillierParamsResult',
    full_name='org.interconnection.v2.protocol.PaillierParamsResult',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name='key_size',
            full_name='org.interconnection.v2.protocol.PaillierParamsResult.key_size',
            index=0,
            number=1,
            type=5,
            cpp_type=1,
            label=1,
            has_default_value=False,
            default_value=0,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[],
    serialized_start=394,
    serialized_end=434,
)

_PHEPROTOCOLPROPOSAL.fields_by_name[
    'supported_phe_params'
].message_type = google_dot_protobuf_dot_any__pb2._ANY
_PHEPROTOCOLRESULT.fields_by_name[
    'phe_param'
].message_type = google_dot_protobuf_dot_any__pb2._ANY
DESCRIPTOR.message_types_by_name['PheProtocolProposal'] = _PHEPROTOCOLPROPOSAL
DESCRIPTOR.message_types_by_name['PaillierParamsProposal'] = _PAILLIERPARAMSPROPOSAL
DESCRIPTOR.message_types_by_name['PheProtocolResult'] = _PHEPROTOCOLRESULT
DESCRIPTOR.message_types_by_name['PaillierParamsResult'] = _PAILLIERPARAMSRESULT
DESCRIPTOR.enum_types_by_name['PheAlgo'] = _PHEALGO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PheProtocolProposal = _reflection.GeneratedProtocolMessageType(
    'PheProtocolProposal',
    (_message.Message,),
    {
        'DESCRIPTOR': _PHEPROTOCOLPROPOSAL,
        '__module__': 'secretflow.ic.proto.handshake.protocol_family.phe_pb2'
        # @@protoc_insertion_point(class_scope:org.interconnection.v2.protocol.PheProtocolProposal)
    },
)
_sym_db.RegisterMessage(PheProtocolProposal)

PaillierParamsProposal = _reflection.GeneratedProtocolMessageType(
    'PaillierParamsProposal',
    (_message.Message,),
    {
        'DESCRIPTOR': _PAILLIERPARAMSPROPOSAL,
        '__module__': 'secretflow.ic.proto.handshake.protocol_family.phe_pb2'
        # @@protoc_insertion_point(class_scope:org.interconnection.v2.protocol.PaillierParamsProposal)
    },
)
_sym_db.RegisterMessage(PaillierParamsProposal)

PheProtocolResult = _reflection.GeneratedProtocolMessageType(
    'PheProtocolResult',
    (_message.Message,),
    {
        'DESCRIPTOR': _PHEPROTOCOLRESULT,
        '__module__': 'secretflow.ic.proto.handshake.protocol_family.phe_pb2'
        # @@protoc_insertion_point(class_scope:org.interconnection.v2.protocol.PheProtocolResult)
    },
)
_sym_db.RegisterMessage(PheProtocolResult)

PaillierParamsResult = _reflection.GeneratedProtocolMessageType(
    'PaillierParamsResult',
    (_message.Message,),
    {
        'DESCRIPTOR': _PAILLIERPARAMSRESULT,
        '__module__': 'secretflow.ic.proto.handshake.protocol_family.phe_pb2'
        # @@protoc_insertion_point(class_scope:org.interconnection.v2.protocol.PaillierParamsResult)
    },
)
_sym_db.RegisterMessage(PaillierParamsResult)


# @@protoc_insertion_point(module_scope)
