# @package _global_

# specify here default configuration
# order of defaults determines the order in which configs override each other
defaults:
  - path: default
  - model: GLORYSplit
  - logger: wandb
  - dataset: MINDlarge
  - _self_

seed: 3407 # 3407 is all you need
num_epochs: 16
batch_size: 128  # dataloaders'batch_size = batch_size / gpu_num
npratio: 4
accumulation_steps: 1
# final total actual batch_size = batch_size * accumalation_steps
train_mode: true
val_mode: true

num_workers: 4        # Number = nGPU * 4
dropout_probability: 0.2

early_stop_patience: 3
enable_prefetch: true
enable_shuffle: false
log_steps: 1000
load_checkpoint: false
val_steps: 1000

ml_label: default
gpu_num: 1
reprocess: false