# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from secretflow.distributed.fed.proxy.grpc import fed_pb2 as secretflow_dot_distributed_dot_fed_dot_proxy_dot_grpc_dot_fed__pb2


class SfFedProxyStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SendData = channel.unary_unary(
                '/SfFedProxy/SendData',
                request_serializer=secretflow_dot_distributed_dot_fed_dot_proxy_dot_grpc_dot_fed__pb2.SfFedProxySendData.SerializeToString,
                response_deserializer=secretflow_dot_distributed_dot_fed_dot_proxy_dot_grpc_dot_fed__pb2.SfFedProxySendDataResponse.FromString,
                )


class SfFedProxyServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SendData(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SfFedProxyServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SendData': grpc.unary_unary_rpc_method_handler(
                    servicer.SendData,
                    request_deserializer=secretflow_dot_distributed_dot_fed_dot_proxy_dot_grpc_dot_fed__pb2.SfFedProxySendData.FromString,
                    response_serializer=secretflow_dot_distributed_dot_fed_dot_proxy_dot_grpc_dot_fed__pb2.SfFedProxySendDataResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'SfFedProxy', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class SfFedProxy(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SendData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/SfFedProxy/SendData',
            secretflow_dot_distributed_dot_fed_dot_proxy_dot_grpc_dot_fed__pb2.SfFedProxySendData.SerializeToString,
            secretflow_dot_distributed_dot_fed_dot_proxy_dot_grpc_dot_fed__pb2.SfFedProxySendDataResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
