# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: secretflow/distributed/fed/proxy/grpc/fed.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n/secretflow/distributed/fed/proxy/grpc/fed.proto\"D\n\x12SfFedProxySendData\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\x12\x0e\n\x06seq_id\x18\x02 \x01(\x03\x12\x10\n\x08job_name\x18\x03 \x01(\t\":\n\x1aSfFedProxySendDataResponse\x12\x0c\n\x04\x63ode\x18\x01 \x01(\x05\x12\x0e\n\x06result\x18\x02 \x01(\t2L\n\nSfFedProxy\x12>\n\x08SendData\x12\x13.SfFedProxySendData\x1a\x1b.SfFedProxySendDataResponse\"\x00\x42\x03\x80\x01\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'secretflow.distributed.fed.proxy.grpc.fed_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\200\001\001'
  _globals['_SFFEDPROXYSENDDATA']._serialized_start=51
  _globals['_SFFEDPROXYSENDDATA']._serialized_end=119
  _globals['_SFFEDPROXYSENDDATARESPONSE']._serialized_start=121
  _globals['_SFFEDPROXYSENDDATARESPONSE']._serialized_end=179
  _globals['_SFFEDPROXY']._serialized_start=181
  _globals['_SFFEDPROXY']._serialized_end=257
# @@protoc_insertion_point(module_scope)
