# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: secretflow/spec/extend/bin_data.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n%secretflow/spec/extend/bin_data.proto\x12\x16secretflow.spec.extend\"~\n\x03\x42in\x12\x12\n\nleft_bound\x18\x01 \x01(\x02\x12\x13\n\x0bright_bound\x18\x02 \x01(\x02\x12\n\n\x02iv\x18\x03 \x01(\x02\x12\x15\n\rfilling_value\x18\x04 \x01(\x02\x12\x13\n\x0btotal_count\x18\x05 \x01(\x04\x12\x16\n\x0emark_for_merge\x18\x06 \x01(\x08\"\xe3\x01\n\x0cVariableBins\x12\x14\n\x0c\x66\x65\x61ture_name\x18\x01 \x01(\t\x12\x14\n\x0c\x66\x65\x61ture_type\x18\x02 \x01(\t\x12\x17\n\x0fvalid_bin_count\x18\x03 \x01(\x05\x12\n\n\x02iv\x18\x04 \x01(\x02\x12/\n\nvalid_bins\x18\x05 \x03(\x0b\x32\x1b.secretflow.spec.extend.Bin\x12-\n\x08\x65lse_bin\x18\x06 \x01(\x0b\x32\x1b.secretflow.spec.extend.Bin\x12\x12\n\nparty_name\x18\x07 \x01(\t\x12\x0e\n\x06is_woe\x18\x08 \x01(\x08\"W\n\x04\x42ins\x12;\n\rvariable_bins\x18\x01 \x03(\x0b\x32$.secretflow.spec.extend.VariableBins\x12\x12\n\nmodel_hash\x18\x02 \x01(\tB\x1c\n\x1aorg.secretflow.spec.extendb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'secretflow.spec.extend.bin_data_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\032org.secretflow.spec.extend'
  _BIN._serialized_start=65
  _BIN._serialized_end=191
  _VARIABLEBINS._serialized_start=194
  _VARIABLEBINS._serialized_end=421
  _BINS._serialized_start=423
  _BINS._serialized_end=510
# @@protoc_insertion_point(module_scope)
