# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: bin_data.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='bin_data.proto',
  package='secretflow.spec.extend',
  syntax='proto3',
  serialized_options=b'\n\032org.secretflow.spec.extend',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0e\x62in_data.proto\x12\x16secretflow.spec.extend\"r\n\x03\x42in\x12\x12\n\nleft_bound\x18\x01 \x01(\x02\x12\x13\n\x0bright_bound\x18\x02 \x01(\x02\x12\x15\n\rfilling_value\x18\x04 \x01(\x02\x12\x13\n\x0btotal_count\x18\x05 \x01(\x04\x12\x16\n\x0emark_for_merge\x18\x06 \x01(\x08\"\xe3\x01\n\x0cVariableBins\x12\x14\n\x0c\x66\x65\x61ture_name\x18\x01 \x01(\t\x12\x14\n\x0c\x66\x65\x61ture_type\x18\x02 \x01(\t\x12\x17\n\x0fvalid_bin_count\x18\x03 \x01(\x05\x12\n\n\x02iv\x18\x04 \x01(\x02\x12/\n\nvalid_bins\x18\x05 \x03(\x0b\x32\x1b.secretflow.spec.extend.Bin\x12-\n\x08\x65lse_bin\x18\x06 \x01(\x0b\x32\x1b.secretflow.spec.extend.Bin\x12\x12\n\nparty_name\x18\x07 \x01(\t\x12\x0e\n\x06is_woe\x18\x08 \x01(\x08\"W\n\x04\x42ins\x12;\n\rvariable_bins\x18\x01 \x03(\x0b\x32$.secretflow.spec.extend.VariableBins\x12\x12\n\nmodel_hash\x18\x02 \x01(\tB\x1c\n\x1aorg.secretflow.spec.extendb\x06proto3'
)




_BIN = _descriptor.Descriptor(
  name='Bin',
  full_name='secretflow.spec.extend.Bin',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='left_bound', full_name='secretflow.spec.extend.Bin.left_bound', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='right_bound', full_name='secretflow.spec.extend.Bin.right_bound', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='filling_value', full_name='secretflow.spec.extend.Bin.filling_value', index=2,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='total_count', full_name='secretflow.spec.extend.Bin.total_count', index=3,
      number=5, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='mark_for_merge', full_name='secretflow.spec.extend.Bin.mark_for_merge', index=4,
      number=6, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=42,
  serialized_end=156,
)


_VARIABLEBINS = _descriptor.Descriptor(
  name='VariableBins',
  full_name='secretflow.spec.extend.VariableBins',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='feature_name', full_name='secretflow.spec.extend.VariableBins.feature_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='feature_type', full_name='secretflow.spec.extend.VariableBins.feature_type', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='valid_bin_count', full_name='secretflow.spec.extend.VariableBins.valid_bin_count', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='iv', full_name='secretflow.spec.extend.VariableBins.iv', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='valid_bins', full_name='secretflow.spec.extend.VariableBins.valid_bins', index=4,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='else_bin', full_name='secretflow.spec.extend.VariableBins.else_bin', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='party_name', full_name='secretflow.spec.extend.VariableBins.party_name', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='is_woe', full_name='secretflow.spec.extend.VariableBins.is_woe', index=7,
      number=8, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=159,
  serialized_end=386,
)


_BINS = _descriptor.Descriptor(
  name='Bins',
  full_name='secretflow.spec.extend.Bins',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='variable_bins', full_name='secretflow.spec.extend.Bins.variable_bins', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='model_hash', full_name='secretflow.spec.extend.Bins.model_hash', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=388,
  serialized_end=475,
)

_VARIABLEBINS.fields_by_name['valid_bins'].message_type = _BIN
_VARIABLEBINS.fields_by_name['else_bin'].message_type = _BIN
_BINS.fields_by_name['variable_bins'].message_type = _VARIABLEBINS
DESCRIPTOR.message_types_by_name['Bin'] = _BIN
DESCRIPTOR.message_types_by_name['VariableBins'] = _VARIABLEBINS
DESCRIPTOR.message_types_by_name['Bins'] = _BINS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Bin = _reflection.GeneratedProtocolMessageType('Bin', (_message.Message,), {
  'DESCRIPTOR' : _BIN,
  '__module__' : 'bin_data_pb2'
  # @@protoc_insertion_point(class_scope:secretflow.spec.extend.Bin)
  })
_sym_db.RegisterMessage(Bin)

VariableBins = _reflection.GeneratedProtocolMessageType('VariableBins', (_message.Message,), {
  'DESCRIPTOR' : _VARIABLEBINS,
  '__module__' : 'bin_data_pb2'
  # @@protoc_insertion_point(class_scope:secretflow.spec.extend.VariableBins)
  })
_sym_db.RegisterMessage(VariableBins)

Bins = _reflection.GeneratedProtocolMessageType('Bins', (_message.Message,), {
  'DESCRIPTOR' : _BINS,
  '__module__' : 'bin_data_pb2'
  # @@protoc_insertion_point(class_scope:secretflow.spec.extend.Bins)
  })
_sym_db.RegisterMessage(Bins)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
