# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: secretflow/spec/extend/calculate_rules.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n,secretflow/spec/extend/calculate_rules.proto\x12\x16secretflow.spec.extend\"\xab\x02\n\x10\x43\x61lculateOpRules\x12;\n\x02op\x18\x01 \x01(\x0e\x32/.secretflow.spec.extend.CalculateOpRules.OpType\x12\x10\n\x08operands\x18\x02 \x03(\t\x12\x14\n\x0cnew_col_name\x18\x03 \x01(\t\"\xb1\x01\n\x06OpType\x12\t\n\x05INVAL\x10\x00\x12\x0f\n\x0bSTANDARDIZE\x10\x01\x12\x11\n\rNORMALIZATION\x10\x02\x12\x0f\n\x0bRANGE_LIMIT\x10\x03\x12\t\n\x05UNARY\x10\x04\x12\x0e\n\nRECIPROCAL\x10\x05\x12\t\n\x05ROUND\x10\x06\x12\r\n\tLOG_ROUND\x10\x07\x12\x08\n\x04SQRT\x10\x08\x12\x07\n\x03LOG\x10\t\x12\x07\n\x03\x45XP\x10\n\x12\n\n\x06LENGTH\x10\x0b\x12\n\n\x06SUBSTR\x10\x0c\x42\x1c\n\x1aorg.secretflow.spec.extendb\x06proto3')



_CALCULATEOPRULES = DESCRIPTOR.message_types_by_name['CalculateOpRules']
_CALCULATEOPRULES_OPTYPE = _CALCULATEOPRULES.enum_types_by_name['OpType']
CalculateOpRules = _reflection.GeneratedProtocolMessageType('CalculateOpRules', (_message.Message,), {
  'DESCRIPTOR' : _CALCULATEOPRULES,
  '__module__' : 'secretflow.spec.extend.calculate_rules_pb2'
  # @@protoc_insertion_point(class_scope:secretflow.spec.extend.CalculateOpRules)
  })
_sym_db.RegisterMessage(CalculateOpRules)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\032org.secretflow.spec.extend'
  _CALCULATEOPRULES._serialized_start=73
  _CALCULATEOPRULES._serialized_end=372
  _CALCULATEOPRULES_OPTYPE._serialized_start=195
  _CALCULATEOPRULES_OPTYPE._serialized_end=372
# @@protoc_insertion_point(module_scope)
