"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
Copyright 2023 Ant Group Co., Ltd.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
"""

import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class DeviceObjectCollection(google.protobuf.message.Message):
    """Descibes public storage info for a collection of Device Objects."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing.final
    class DeviceObject(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        TYPE_FIELD_NUMBER: builtins.int
        DATA_REF_IDXS_FIELD_NUMBER: builtins.int
        type: builtins.str
        """Supported: `spu \\| pyu`"""
        @property
        def data_ref_idxs(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.int]:
            """Index of data_ref in the parent DistData message."""

        def __init__(
            self,
            *,
            type: builtins.str = ...,
            data_ref_idxs: collections.abc.Iterable[builtins.int] | None = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing.Literal["data_ref_idxs", b"data_ref_idxs", "type", b"type"]) -> None: ...

    OBJS_FIELD_NUMBER: builtins.int
    PUBLIC_INFO_FIELD_NUMBER: builtins.int
    public_info: builtins.str
    """Any public information."""
    @property
    def objs(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___DeviceObjectCollection.DeviceObject]: ...
    def __init__(
        self,
        *,
        objs: collections.abc.Iterable[global___DeviceObjectCollection.DeviceObject] | None = ...,
        public_info: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["objs", b"objs", "public_info", b"public_info"]) -> None: ...

global___DeviceObjectCollection = DeviceObjectCollection
