"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
Copyright 2023 Ant Group Co., Ltd.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
"""

import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class ColumnQuery(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    class _AggregationFunction:
        ValueType = typing.NewType("ValueType", builtins.int)
        V: typing_extensions.TypeAlias = ValueType

    class _AggregationFunctionEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[ColumnQuery._AggregationFunction.ValueType], builtins.type):
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        INVAL: ColumnQuery._AggregationFunction.ValueType  # 0
        SUM: ColumnQuery._AggregationFunction.ValueType  # 1
        MEAN: ColumnQuery._AggregationFunction.ValueType  # 2
        VAR: ColumnQuery._AggregationFunction.ValueType  # 3
        MIN: ColumnQuery._AggregationFunction.ValueType  # 4
        MAX: ColumnQuery._AggregationFunction.ValueType  # 5
        COUNT: ColumnQuery._AggregationFunction.ValueType  # 6

    class AggregationFunction(_AggregationFunction, metaclass=_AggregationFunctionEnumTypeWrapper): ...
    INVAL: ColumnQuery.AggregationFunction.ValueType  # 0
    SUM: ColumnQuery.AggregationFunction.ValueType  # 1
    MEAN: ColumnQuery.AggregationFunction.ValueType  # 2
    VAR: ColumnQuery.AggregationFunction.ValueType  # 3
    MIN: ColumnQuery.AggregationFunction.ValueType  # 4
    MAX: ColumnQuery.AggregationFunction.ValueType  # 5
    COUNT: ColumnQuery.AggregationFunction.ValueType  # 6

    FUNCTION_FIELD_NUMBER: builtins.int
    COLUMN_NAME_FIELD_NUMBER: builtins.int
    function: global___ColumnQuery.AggregationFunction.ValueType
    column_name: builtins.str
    def __init__(
        self,
        *,
        function: global___ColumnQuery.AggregationFunction.ValueType = ...,
        column_name: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["column_name", b"column_name", "function", b"function"]) -> None: ...

global___ColumnQuery = ColumnQuery

@typing.final
class GroupbyAggregationConfig(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    COLUMN_QUERIES_FIELD_NUMBER: builtins.int
    @property
    def column_queries(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___ColumnQuery]: ...
    def __init__(
        self,
        *,
        column_queries: collections.abc.Iterable[global___ColumnQuery] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["column_queries", b"column_queries"]) -> None: ...

global___GroupbyAggregationConfig = GroupbyAggregationConfig
