# -*- coding: utf-8 -*-
# Copyright 2024 Ant Group Co., Ltd.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: secretflow/spec/extend/groupby_aggregation_config.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n7secretflow/spec/extend/groupby_aggregation_config.proto\x12\x16secretflow.spec.extend\"\xc8\x01\n\x0b\x43olumnQuery\x12I\n\x08\x66unction\x18\x01 \x01(\x0e\x32\x37.secretflow.spec.extend.ColumnQuery.AggregationFunction\x12\x13\n\x0b\x63olumn_name\x18\x02 \x01(\t\"Y\n\x13\x41ggregationFunction\x12\t\n\x05INVAL\x10\x00\x12\x07\n\x03SUM\x10\x01\x12\x08\n\x04MEAN\x10\x02\x12\x07\n\x03VAR\x10\x03\x12\x07\n\x03MIN\x10\x04\x12\x07\n\x03MAX\x10\x05\x12\t\n\x05\x43OUNT\x10\x06\"W\n\x18GroupbyAggregationConfig\x12;\n\x0e\x63olumn_queries\x18\x01 \x03(\x0b\x32#.secretflow.spec.extend.ColumnQueryB\x1c\n\x1aorg.secretflow.spec.extendb\x06proto3')



_COLUMNQUERY = DESCRIPTOR.message_types_by_name['ColumnQuery']
_GROUPBYAGGREGATIONCONFIG = DESCRIPTOR.message_types_by_name['GroupbyAggregationConfig']
_COLUMNQUERY_AGGREGATIONFUNCTION = _COLUMNQUERY.enum_types_by_name['AggregationFunction']
ColumnQuery = _reflection.GeneratedProtocolMessageType('ColumnQuery', (_message.Message,), {
  'DESCRIPTOR' : _COLUMNQUERY,
  '__module__' : 'secretflow.spec.extend.groupby_aggregation_config_pb2'
  # @@protoc_insertion_point(class_scope:secretflow.spec.extend.ColumnQuery)
  })
_sym_db.RegisterMessage(ColumnQuery)

GroupbyAggregationConfig = _reflection.GeneratedProtocolMessageType('GroupbyAggregationConfig', (_message.Message,), {
  'DESCRIPTOR' : _GROUPBYAGGREGATIONCONFIG,
  '__module__' : 'secretflow.spec.extend.groupby_aggregation_config_pb2'
  # @@protoc_insertion_point(class_scope:secretflow.spec.extend.GroupbyAggregationConfig)
  })
_sym_db.RegisterMessage(GroupbyAggregationConfig)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\032org.secretflow.spec.extend'
  _COLUMNQUERY._serialized_start=84
  _COLUMNQUERY._serialized_end=284
  _COLUMNQUERY_AGGREGATIONFUNCTION._serialized_start=195
  _COLUMNQUERY_AGGREGATIONFUNCTION._serialized_end=284
  _GROUPBYAGGREGATIONCONFIG._serialized_start=286
  _GROUPBYAGGREGATIONCONFIG._serialized_end=373
# @@protoc_insertion_point(module_scope)
