# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: linear_model.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='linear_model.proto',
  package='secretflow.spec.extend',
  syntax='proto3',
  serialized_options=b'\n\032org.secretflow.spec.extend',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x12linear_model.proto\x12\x16secretflow.spec.extend\"L\n\rFeatureWeight\x12\x14\n\x0c\x66\x65\x61ture_name\x18\x01 \x01(\t\x12\r\n\x05party\x18\x02 \x01(\t\x12\x16\n\x0e\x66\x65\x61ture_weight\x18\x03 \x01(\x02\"o\n\x0bLinearModel\x12>\n\x0f\x66\x65\x61ture_weights\x18\x01 \x03(\x0b\x32%.secretflow.spec.extend.FeatureWeight\x12\x0c\n\x04\x62ias\x18\x02 \x01(\x02\x12\x12\n\nmodel_hash\x18\x03 \x01(\tB\x1c\n\x1aorg.secretflow.spec.extendb\x06proto3'
)




_FEATUREWEIGHT = _descriptor.Descriptor(
  name='FeatureWeight',
  full_name='secretflow.spec.extend.FeatureWeight',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='feature_name', full_name='secretflow.spec.extend.FeatureWeight.feature_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='party', full_name='secretflow.spec.extend.FeatureWeight.party', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='feature_weight', full_name='secretflow.spec.extend.FeatureWeight.feature_weight', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=46,
  serialized_end=122,
)


_LINEARMODEL = _descriptor.Descriptor(
  name='LinearModel',
  full_name='secretflow.spec.extend.LinearModel',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='feature_weights', full_name='secretflow.spec.extend.LinearModel.feature_weights', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='bias', full_name='secretflow.spec.extend.LinearModel.bias', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='model_hash', full_name='secretflow.spec.extend.LinearModel.model_hash', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=124,
  serialized_end=235,
)

_LINEARMODEL.fields_by_name['feature_weights'].message_type = _FEATUREWEIGHT
DESCRIPTOR.message_types_by_name['FeatureWeight'] = _FEATUREWEIGHT
DESCRIPTOR.message_types_by_name['LinearModel'] = _LINEARMODEL
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

FeatureWeight = _reflection.GeneratedProtocolMessageType('FeatureWeight', (_message.Message,), {
  'DESCRIPTOR' : _FEATUREWEIGHT,
  '__module__' : 'linear_model_pb2'
  # @@protoc_insertion_point(class_scope:secretflow.spec.extend.FeatureWeight)
  })
_sym_db.RegisterMessage(FeatureWeight)

LinearModel = _reflection.GeneratedProtocolMessageType('LinearModel', (_message.Message,), {
  'DESCRIPTOR' : _LINEARMODEL,
  '__module__' : 'linear_model_pb2'
  # @@protoc_insertion_point(class_scope:secretflow.spec.extend.LinearModel)
  })
_sym_db.RegisterMessage(LinearModel)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
