# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: secretflow/spec/extend/linear_model.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n)secretflow/spec/extend/linear_model.proto\x12\x16secretflow.spec.extend\"L\n\rFeatureWeight\x12\x14\n\x0c\x66\x65\x61ture_name\x18\x01 \x01(\t\x12\r\n\x05party\x18\x02 \x01(\t\x12\x16\n\x0e\x66\x65\x61ture_weight\x18\x03 \x01(\x02\"o\n\x0bLinearModel\x12>\n\x0f\x66\x65\x61ture_weights\x18\x01 \x03(\x0b\x32%.secretflow.spec.extend.FeatureWeight\x12\x0c\n\x04\x62ias\x18\x02 \x01(\x02\x12\x12\n\nmodel_hash\x18\x03 \x01(\tB\x1c\n\x1aorg.secretflow.spec.extendb\x06proto3')



_FEATUREWEIGHT = DESCRIPTOR.message_types_by_name['FeatureWeight']
_LINEARMODEL = DESCRIPTOR.message_types_by_name['LinearModel']
FeatureWeight = _reflection.GeneratedProtocolMessageType('FeatureWeight', (_message.Message,), {
  'DESCRIPTOR' : _FEATUREWEIGHT,
  '__module__' : 'secretflow.spec.extend.linear_model_pb2'
  # @@protoc_insertion_point(class_scope:secretflow.spec.extend.FeatureWeight)
  })
_sym_db.RegisterMessage(FeatureWeight)

LinearModel = _reflection.GeneratedProtocolMessageType('LinearModel', (_message.Message,), {
  'DESCRIPTOR' : _LINEARMODEL,
  '__module__' : 'secretflow.spec.extend.linear_model_pb2'
  # @@protoc_insertion_point(class_scope:secretflow.spec.extend.LinearModel)
  })
_sym_db.RegisterMessage(LinearModel)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\032org.secretflow.spec.extend'
  _FEATUREWEIGHT._serialized_start=69
  _FEATUREWEIGHT._serialized_end=145
  _LINEARMODEL._serialized_start=147
  _LINEARMODEL._serialized_end=258
# @@protoc_insertion_point(module_scope)
