# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: secretflow/protos/secretflow/spec/extend/preprocessing_meta.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nAsecretflow/protos/secretflow/spec/extend/preprocessing_meta.proto\x12\x16secretflow.spec.extend\"+\n\rAddColumnInfo\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0c\n\x04type\x18\x02 \x01(\t\"\x9f\x01\n\x0fTableMetaChange\x12\x14\n\x0c\x64rop_columns\x18\x01 \x03(\t\x12;\n\x0cnew_features\x18\x03 \x03(\x0b\x32%.secretflow.spec.extend.AddColumnInfo\x12\x39\n\nnew_labels\x18\x04 \x03(\x0b\x32%.secretflow.spec.extend.AddColumnInfoB\x1c\n\x1aorg.secretflow.spec.extendb\x06proto3')



_ADDCOLUMNINFO = DESCRIPTOR.message_types_by_name['AddColumnInfo']
_TABLEMETACHANGE = DESCRIPTOR.message_types_by_name['TableMetaChange']
AddColumnInfo = _reflection.GeneratedProtocolMessageType('AddColumnInfo', (_message.Message,), {
  'DESCRIPTOR' : _ADDCOLUMNINFO,
  '__module__' : 'secretflow.protos.secretflow.spec.extend.preprocessing_meta_pb2'
  # @@protoc_insertion_point(class_scope:secretflow.spec.extend.AddColumnInfo)
  })
_sym_db.RegisterMessage(AddColumnInfo)

TableMetaChange = _reflection.GeneratedProtocolMessageType('TableMetaChange', (_message.Message,), {
  'DESCRIPTOR' : _TABLEMETACHANGE,
  '__module__' : 'secretflow.protos.secretflow.spec.extend.preprocessing_meta_pb2'
  # @@protoc_insertion_point(class_scope:secretflow.spec.extend.TableMetaChange)
  })
_sym_db.RegisterMessage(TableMetaChange)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\032org.secretflow.spec.extend'
  _ADDCOLUMNINFO._serialized_start=93
  _ADDCOLUMNINFO._serialized_end=136
  _TABLEMETACHANGE._serialized_start=139
  _TABLEMETACHANGE._serialized_end=298
# @@protoc_insertion_point(module_scope)
