# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: secretflow/ic/proto/handshake/algos/sgb.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n-secretflow/ic/proto/handshake/algos/sgb.proto\x12\x1corg.interconnection.v2.algos\"\x97\x01\n\x11SgbParamsProposal\x12\x1a\n\x12supported_versions\x18\x01 \x03(\x05\x12\x1e\n\x16support_completely_sgb\x18\x64 \x01(\x08\x12\"\n\x1asupport_row_sample_by_tree\x18\x65 \x01(\x08\x12\"\n\x1asupport_col_sample_by_tree\x18\x66 \x01(\x08\"\xb0\x01\n\x0fSgbParamsResult\x12\x0f\n\x07version\x18\x01 \x01(\x05\x12\x11\n\tnum_round\x18\x02 \x01(\x05\x12\x11\n\tmax_depth\x18\x03 \x01(\x05\x12\x1a\n\x12row_sample_by_tree\x18\x04 \x01(\x01\x12\x1a\n\x12\x63ol_sample_by_tree\x18\x05 \x01(\x01\x12\x12\n\nbucket_eps\x18\x06 \x01(\x01\x12\x1a\n\x12use_completely_sgb\x18\x64 \x01(\x08\x62\x06proto3')



_SGBPARAMSPROPOSAL = DESCRIPTOR.message_types_by_name['SgbParamsProposal']
_SGBPARAMSRESULT = DESCRIPTOR.message_types_by_name['SgbParamsResult']
SgbParamsProposal = _reflection.GeneratedProtocolMessageType('SgbParamsProposal', (_message.Message,), {
  'DESCRIPTOR' : _SGBPARAMSPROPOSAL,
  '__module__' : 'secretflow.ic.proto.handshake.algos.sgb_pb2'
  # @@protoc_insertion_point(class_scope:org.interconnection.v2.algos.SgbParamsProposal)
  })
_sym_db.RegisterMessage(SgbParamsProposal)

SgbParamsResult = _reflection.GeneratedProtocolMessageType('SgbParamsResult', (_message.Message,), {
  'DESCRIPTOR' : _SGBPARAMSRESULT,
  '__module__' : 'secretflow.ic.proto.handshake.algos.sgb_pb2'
  # @@protoc_insertion_point(class_scope:org.interconnection.v2.algos.SgbParamsResult)
  })
_sym_db.RegisterMessage(SgbParamsResult)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SGBPARAMSPROPOSAL._serialized_start=80
  _SGBPARAMSPROPOSAL._serialized_end=231
  _SGBPARAMSRESULT._serialized_start=234
  _SGBPARAMSRESULT._serialized_end=410
# @@protoc_insertion_point(module_scope)
