# Evaluate PII Extraction
dataset_args:
  dataset_path: ../src/pii_leakage/extern/echr
  dataset_mode: undefended
  sample_duplication_rate: 1

attack_args:
  attack_name: naive_extraction
  sampling_rate: 15000
  seq_len: 256

model_args:
  architecture: gpt2-large
  pre_trained: True   # Start from a pre-trained checkpoint
  model_ckpt: ../examples/models/echr-gpt2-large # Edit this path to try your own model.
  model_revision: main
  torch_dtype: bfloat16
  attn_implementation: flash_attention_2
  # LoRA arguments
  load_in_4bit: False
  use_peft: False


ner_args:
  ner: flair
  ner_model: flair/ner-english-ontonotes-large
  anon_token: <MASK>
  anonymize: False

env_args:
  eval_batch_size: 32