# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: secretflow/ic/proto/common/header.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\'secretflow/ic/proto/common/header.proto\x12\x13org.interconnection\"7\n\x0eResponseHeader\x12\x12\n\nerror_code\x18\x01 \x01(\x05\x12\x11\n\terror_msg\x18\x02 \x01(\t*\xf3\x01\n\tErrorCode\x12\x06\n\x02OK\x10\x00\x12\x14\n\rGENERIC_ERROR\x10\xe0\x98\xea\x0e\x12\x17\n\x10UNEXPECTED_ERROR\x10\xe1\x98\xea\x0e\x12\x14\n\rNETWORK_ERROR\x10\xe2\x98\xea\x0e\x12\x16\n\x0fINVALID_REQUEST\x10\xc4\x99\xea\x0e\x12\x17\n\x10INVALID_RESOURCE\x10\xc5\x99\xea\x0e\x12\x18\n\x11HANDSHAKE_REFUSED\x10\xa8\x9a\xea\x0e\x12\x1a\n\x13UNSUPPORTED_VERSION\x10\xa9\x9a\xea\x0e\x12\x17\n\x10UNSUPPORTED_ALGO\x10\xaa\x9a\xea\x0e\x12\x19\n\x12UNSUPPORTED_PARAMS\x10\xab\x9a\xea\x0e\x62\x06proto3')

_ERRORCODE = DESCRIPTOR.enum_types_by_name['ErrorCode']
ErrorCode = enum_type_wrapper.EnumTypeWrapper(_ERRORCODE)
OK = 0
GENERIC_ERROR = 31100000
UNEXPECTED_ERROR = 31100001
NETWORK_ERROR = 31100002
INVALID_REQUEST = 31100100
INVALID_RESOURCE = 31100101
HANDSHAKE_REFUSED = 31100200
UNSUPPORTED_VERSION = 31100201
UNSUPPORTED_ALGO = 31100202
UNSUPPORTED_PARAMS = 31100203


_RESPONSEHEADER = DESCRIPTOR.message_types_by_name['ResponseHeader']
ResponseHeader = _reflection.GeneratedProtocolMessageType('ResponseHeader', (_message.Message,), {
  'DESCRIPTOR' : _RESPONSEHEADER,
  '__module__' : 'secretflow.ic.proto.common.header_pb2'
  # @@protoc_insertion_point(class_scope:org.interconnection.ResponseHeader)
  })
_sym_db.RegisterMessage(ResponseHeader)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _ERRORCODE._serialized_start=122
  _ERRORCODE._serialized_end=365
  _RESPONSEHEADER._serialized_start=64
  _RESPONSEHEADER._serialized_end=119
# @@protoc_insertion_point(module_scope)
