# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: secretflow/ic/proto/common/header.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='secretflow/ic/proto/common/header.proto',
  package='org.interconnection',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\'secretflow/ic/proto/common/header.proto\x12\x13org.interconnection\"7\n\x0eResponseHeader\x12\x12\n\nerror_code\x18\x01 \x01(\x05\x12\x11\n\terror_msg\x18\x02 \x01(\t*\xf3\x01\n\tErrorCode\x12\x06\n\x02OK\x10\x00\x12\x14\n\rGENERIC_ERROR\x10\xe0\x98\xea\x0e\x12\x17\n\x10UNEXPECTED_ERROR\x10\xe1\x98\xea\x0e\x12\x14\n\rNETWORK_ERROR\x10\xe2\x98\xea\x0e\x12\x16\n\x0fINVALID_REQUEST\x10\xc4\x99\xea\x0e\x12\x17\n\x10INVALID_RESOURCE\x10\xc5\x99\xea\x0e\x12\x18\n\x11HANDSHAKE_REFUSED\x10\xa8\x9a\xea\x0e\x12\x1a\n\x13UNSUPPORTED_VERSION\x10\xa9\x9a\xea\x0e\x12\x17\n\x10UNSUPPORTED_ALGO\x10\xaa\x9a\xea\x0e\x12\x19\n\x12UNSUPPORTED_PARAMS\x10\xab\x9a\xea\x0e\x62\x06proto3'
)

_ERRORCODE = _descriptor.EnumDescriptor(
  name='ErrorCode',
  full_name='org.interconnection.ErrorCode',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='OK', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='GENERIC_ERROR', index=1, number=31100000,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='UNEXPECTED_ERROR', index=2, number=31100001,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='NETWORK_ERROR', index=3, number=31100002,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='INVALID_REQUEST', index=4, number=31100100,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='INVALID_RESOURCE', index=5, number=31100101,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='HANDSHAKE_REFUSED', index=6, number=31100200,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='UNSUPPORTED_VERSION', index=7, number=31100201,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='UNSUPPORTED_ALGO', index=8, number=31100202,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='UNSUPPORTED_PARAMS', index=9, number=31100203,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=122,
  serialized_end=365,
)
_sym_db.RegisterEnumDescriptor(_ERRORCODE)

ErrorCode = enum_type_wrapper.EnumTypeWrapper(_ERRORCODE)
OK = 0
GENERIC_ERROR = 31100000
UNEXPECTED_ERROR = 31100001
NETWORK_ERROR = 31100002
INVALID_REQUEST = 31100100
INVALID_RESOURCE = 31100101
HANDSHAKE_REFUSED = 31100200
UNSUPPORTED_VERSION = 31100201
UNSUPPORTED_ALGO = 31100202
UNSUPPORTED_PARAMS = 31100203



_RESPONSEHEADER = _descriptor.Descriptor(
  name='ResponseHeader',
  full_name='org.interconnection.ResponseHeader',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='error_code', full_name='org.interconnection.ResponseHeader.error_code', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='error_msg', full_name='org.interconnection.ResponseHeader.error_msg', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=64,
  serialized_end=119,
)

DESCRIPTOR.message_types_by_name['ResponseHeader'] = _RESPONSEHEADER
DESCRIPTOR.enum_types_by_name['ErrorCode'] = _ERRORCODE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ResponseHeader = _reflection.GeneratedProtocolMessageType('ResponseHeader', (_message.Message,), {
  'DESCRIPTOR' : _RESPONSEHEADER,
  '__module__' : 'secretflow.ic.proto.common.header_pb2'
  # @@protoc_insertion_point(class_scope:org.interconnection.ResponseHeader)
  })
_sym_db.RegisterMessage(ResponseHeader)


# @@protoc_insertion_point(module_scope)
