# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: secretflow/protos/component/data_def.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import any_pb2 as google_dot_protobuf_dot_any__pb2
from secretflow.protos.component import cluster_pb2 as secretflow_dot_protos_dot_component_dot_cluster__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='secretflow/protos/component/data_def.proto',
  package='secretflow.component',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n*secretflow/protos/component/data_def.proto\x12\x14secretflow.component\x1a\x19google/protobuf/any.proto\x1a)secretflow/protos/component/cluster.proto\"W\n\nSystemInfo\x12\x10\n\x08\x61pp_name\x18\x01 \x01(\t\x12\x37\n\nsecretflow\x18\x02 \x01(\x0b\x32#.secretflow.component.SFClusterDesc\"\xdf\x01\n\x08\x44istData\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0c\n\x04type\x18\x02 \x01(\t\x12\x31\n\x07sysinfo\x18\x03 \x01(\x0b\x32 .secretflow.component.SystemInfo\x12\"\n\x04meta\x18\x04 \x01(\x0b\x32\x14.google.protobuf.Any\x12\x39\n\tdata_refs\x18\x05 \x03(\x0b\x32&.secretflow.component.DistData.DataRef\x1a%\n\x07\x44\x61taRef\x12\x0b\n\x03uri\x18\x01 \x01(\t\x12\r\n\x05party\x18\x02 \x01(\t\"\x88\x01\n\x06VTable\x12\x32\n\x06slices\x18\x01 \x03(\x0b\x32\".secretflow.component.VTable.Slice\x12\x11\n\tnum_lines\x18\x02 \x01(\x03\x12\x0e\n\x06\x66ormat\x18\x03 \x01(\t\x1a\'\n\x05Slice\x12\r\n\x05types\x18\x01 \x03(\t\x12\x0f\n\x07headers\x18\x02 \x03(\tb\x06proto3'
  ,
  dependencies=[google_dot_protobuf_dot_any__pb2.DESCRIPTOR,secretflow_dot_protos_dot_component_dot_cluster__pb2.DESCRIPTOR,])




_SYSTEMINFO = _descriptor.Descriptor(
  name='SystemInfo',
  full_name='secretflow.component.SystemInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='app_name', full_name='secretflow.component.SystemInfo.app_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='secretflow', full_name='secretflow.component.SystemInfo.secretflow', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=138,
  serialized_end=225,
)


_DISTDATA_DATAREF = _descriptor.Descriptor(
  name='DataRef',
  full_name='secretflow.component.DistData.DataRef',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='uri', full_name='secretflow.component.DistData.DataRef.uri', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='party', full_name='secretflow.component.DistData.DataRef.party', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=414,
  serialized_end=451,
)

_DISTDATA = _descriptor.Descriptor(
  name='DistData',
  full_name='secretflow.component.DistData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='secretflow.component.DistData.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='type', full_name='secretflow.component.DistData.type', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='sysinfo', full_name='secretflow.component.DistData.sysinfo', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='meta', full_name='secretflow.component.DistData.meta', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='data_refs', full_name='secretflow.component.DistData.data_refs', index=4,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_DISTDATA_DATAREF, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=228,
  serialized_end=451,
)


_VTABLE_SLICE = _descriptor.Descriptor(
  name='Slice',
  full_name='secretflow.component.VTable.Slice',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='types', full_name='secretflow.component.VTable.Slice.types', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='headers', full_name='secretflow.component.VTable.Slice.headers', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=551,
  serialized_end=590,
)

_VTABLE = _descriptor.Descriptor(
  name='VTable',
  full_name='secretflow.component.VTable',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='slices', full_name='secretflow.component.VTable.slices', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='num_lines', full_name='secretflow.component.VTable.num_lines', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='format', full_name='secretflow.component.VTable.format', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_VTABLE_SLICE, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=454,
  serialized_end=590,
)

_SYSTEMINFO.fields_by_name['secretflow'].message_type = secretflow_dot_protos_dot_component_dot_cluster__pb2._SFCLUSTERDESC
_DISTDATA_DATAREF.containing_type = _DISTDATA
_DISTDATA.fields_by_name['sysinfo'].message_type = _SYSTEMINFO
_DISTDATA.fields_by_name['meta'].message_type = google_dot_protobuf_dot_any__pb2._ANY
_DISTDATA.fields_by_name['data_refs'].message_type = _DISTDATA_DATAREF
_VTABLE_SLICE.containing_type = _VTABLE
_VTABLE.fields_by_name['slices'].message_type = _VTABLE_SLICE
DESCRIPTOR.message_types_by_name['SystemInfo'] = _SYSTEMINFO
DESCRIPTOR.message_types_by_name['DistData'] = _DISTDATA
DESCRIPTOR.message_types_by_name['VTable'] = _VTABLE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SystemInfo = _reflection.GeneratedProtocolMessageType('SystemInfo', (_message.Message,), {
  'DESCRIPTOR' : _SYSTEMINFO,
  '__module__' : 'secretflow.protos.component.data_def_pb2'
  # @@protoc_insertion_point(class_scope:secretflow.component.SystemInfo)
  })
_sym_db.RegisterMessage(SystemInfo)

DistData = _reflection.GeneratedProtocolMessageType('DistData', (_message.Message,), {

  'DataRef' : _reflection.GeneratedProtocolMessageType('DataRef', (_message.Message,), {
    'DESCRIPTOR' : _DISTDATA_DATAREF,
    '__module__' : 'secretflow.protos.component.data_def_pb2'
    # @@protoc_insertion_point(class_scope:secretflow.component.DistData.DataRef)
    })
  ,
  'DESCRIPTOR' : _DISTDATA,
  '__module__' : 'secretflow.protos.component.data_def_pb2'
  # @@protoc_insertion_point(class_scope:secretflow.component.DistData)
  })
_sym_db.RegisterMessage(DistData)
_sym_db.RegisterMessage(DistData.DataRef)

VTable = _reflection.GeneratedProtocolMessageType('VTable', (_message.Message,), {

  'Slice' : _reflection.GeneratedProtocolMessageType('Slice', (_message.Message,), {
    'DESCRIPTOR' : _VTABLE_SLICE,
    '__module__' : 'secretflow.protos.component.data_def_pb2'
    # @@protoc_insertion_point(class_scope:secretflow.component.VTable.Slice)
    })
  ,
  'DESCRIPTOR' : _VTABLE,
  '__module__' : 'secretflow.protos.component.data_def_pb2'
  # @@protoc_insertion_point(class_scope:secretflow.component.VTable)
  })
_sym_db.RegisterMessage(VTable)
_sym_db.RegisterMessage(VTable.Slice)


# @@protoc_insertion_point(module_scope)
