# Fine-tune an LM on the enron text dataset.

dataset_args:
  dataset_path: ../src/pii_leakage/extern/echr
  dataset_mode: undefended
  sample_duplication_rate: 1

trainer_args:
  save_steps: 750
  callback_after_n_steps: 750
  num_train_epochs: 4
  gradient_accumulation_steps: 4
  per_device_train_batch_size: 8
  per_device_eval_batch_size: 8
  max_seq_length: 2048

model_args:
  architecture: gpt2
  pre_trained: True   # Start from a pre-trained checkpoint
  model_revision: main
  torch_dtype: bfloat16
  attn_implementation: flash_attention_2
  # LoRA arguments
  load_in_4bit: true
  use_peft: true
  lora_r: 16
  lora_alpha: 32
  lora_dropout: 0.05
  lora_target_modules: all-linear

ner_args:
  ner: flair
  ner_model: flair/ner-english-ontonotes-large
  anon_token: <MASK>
  anonymize: False
