# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: secretflow_serving/protos/compute_trace.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n-secretflow_serving/protos/compute_trace.proto\x12\x1asecretflow.serving.compute\":\n\x06Scalar\x12\r\n\x03i64\x18\x01 \x01(\x03H\x00\x12\x0b\n\x01\x64\x18\x02 \x01(\x01H\x00\x12\x0b\n\x01s\x18\x03 \x01(\tH\x00\x42\x07\n\x05value\"h\n\rFunctionInput\x12\x11\n\x07\x64\x61ta_id\x18\x01 \x01(\x05H\x00\x12;\n\rcustom_scalar\x18\x02 \x01(\x0b\x32\".secretflow.serving.compute.ScalarH\x00\x42\x07\n\x05value\"!\n\x0e\x46unctionOutput\x12\x0f\n\x07\x64\x61ta_id\x18\x01 \x01(\x05\"\xaa\x01\n\rFunctionTrace\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x14\n\x0coption_bytes\x18\x02 \x01(\x0c\x12\x39\n\x06inputs\x18\x03 \x03(\x0b\x32).secretflow.serving.compute.FunctionInput\x12:\n\x06output\x18\x04 \x01(\x0b\x32*.secretflow.serving.compute.FunctionOutput\"\\\n\x0c\x43omputeTrace\x12\x0c\n\x04name\x18\x01 \x01(\t\x12>\n\x0b\x66unc_traces\x18\x02 \x03(\x0b\x32).secretflow.serving.compute.FunctionTrace*\x8c\x01\n\x12\x45xtendFunctionName\x12\x1b\n\x17UNKOWN_EX_FUNCTION_NAME\x10\x00\x12\x11\n\rEFN_TB_COLUMN\x10\x01\x12\x15\n\x11\x45\x46N_TB_ADD_COLUMN\x10\x02\x12\x18\n\x14\x45\x46N_TB_REMOVE_COLUMN\x10\x03\x12\x15\n\x11\x45\x46N_TB_SET_COLUMN\x10\x04\x62\x06proto3')

_EXTENDFUNCTIONNAME = DESCRIPTOR.enum_types_by_name['ExtendFunctionName']
ExtendFunctionName = enum_type_wrapper.EnumTypeWrapper(_EXTENDFUNCTIONNAME)
UNKOWN_EX_FUNCTION_NAME = 0
EFN_TB_COLUMN = 1
EFN_TB_ADD_COLUMN = 2
EFN_TB_REMOVE_COLUMN = 3
EFN_TB_SET_COLUMN = 4


_SCALAR = DESCRIPTOR.message_types_by_name['Scalar']
_FUNCTIONINPUT = DESCRIPTOR.message_types_by_name['FunctionInput']
_FUNCTIONOUTPUT = DESCRIPTOR.message_types_by_name['FunctionOutput']
_FUNCTIONTRACE = DESCRIPTOR.message_types_by_name['FunctionTrace']
_COMPUTETRACE = DESCRIPTOR.message_types_by_name['ComputeTrace']
Scalar = _reflection.GeneratedProtocolMessageType('Scalar', (_message.Message,), {
  'DESCRIPTOR' : _SCALAR,
  '__module__' : 'secretflow_serving.protos.compute_trace_pb2'
  # @@protoc_insertion_point(class_scope:secretflow.serving.compute.Scalar)
  })
_sym_db.RegisterMessage(Scalar)

FunctionInput = _reflection.GeneratedProtocolMessageType('FunctionInput', (_message.Message,), {
  'DESCRIPTOR' : _FUNCTIONINPUT,
  '__module__' : 'secretflow_serving.protos.compute_trace_pb2'
  # @@protoc_insertion_point(class_scope:secretflow.serving.compute.FunctionInput)
  })
_sym_db.RegisterMessage(FunctionInput)

FunctionOutput = _reflection.GeneratedProtocolMessageType('FunctionOutput', (_message.Message,), {
  'DESCRIPTOR' : _FUNCTIONOUTPUT,
  '__module__' : 'secretflow_serving.protos.compute_trace_pb2'
  # @@protoc_insertion_point(class_scope:secretflow.serving.compute.FunctionOutput)
  })
_sym_db.RegisterMessage(FunctionOutput)

FunctionTrace = _reflection.GeneratedProtocolMessageType('FunctionTrace', (_message.Message,), {
  'DESCRIPTOR' : _FUNCTIONTRACE,
  '__module__' : 'secretflow_serving.protos.compute_trace_pb2'
  # @@protoc_insertion_point(class_scope:secretflow.serving.compute.FunctionTrace)
  })
_sym_db.RegisterMessage(FunctionTrace)

ComputeTrace = _reflection.GeneratedProtocolMessageType('ComputeTrace', (_message.Message,), {
  'DESCRIPTOR' : _COMPUTETRACE,
  '__module__' : 'secretflow_serving.protos.compute_trace_pb2'
  # @@protoc_insertion_point(class_scope:secretflow.serving.compute.ComputeTrace)
  })
_sym_db.RegisterMessage(ComputeTrace)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _EXTENDFUNCTIONNAME._serialized_start=546
  _EXTENDFUNCTIONNAME._serialized_end=686
  _SCALAR._serialized_start=77
  _SCALAR._serialized_end=135
  _FUNCTIONINPUT._serialized_start=137
  _FUNCTIONINPUT._serialized_end=241
  _FUNCTIONOUTPUT._serialized_start=243
  _FUNCTIONOUTPUT._serialized_end=276
  _FUNCTIONTRACE._serialized_start=279
  _FUNCTIONTRACE._serialized_end=449
  _COMPUTETRACE._serialized_start=451
  _COMPUTETRACE._serialized_end=543
# @@protoc_insertion_point(module_scope)
