# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: secretflow/protos/pipeline/pipeline.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from secretflow.protos.component import comp_pb2 as secretflow_dot_protos_dot_component_dot_comp__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='secretflow/protos/pipeline/pipeline.proto',
  package='secretflow.pipeline',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n)secretflow/protos/pipeline/pipeline.proto\x12\x13secretflow.pipeline\x1a&secretflow/protos/component/comp.proto\"\xa9\x01\n\x07NodeDef\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0e\n\x06\x64omain\x18\x02 \x01(\t\x12\x0c\n\x04name\x18\x03 \x01(\t\x12\x0f\n\x07version\x18\x04 \x01(\t\x12\x12\n\nattr_paths\x18\x05 \x03(\t\x12.\n\x05\x61ttrs\x18\x06 \x03(\x0b\x32\x1f.secretflow.component.Attribute\x12\x0e\n\x06inputs\x18\x07 \x03(\t\x12\x0f\n\x07outputs\x18\x08 \x03(\t\"F\n\x0bPipelineDef\x12\n\n\x02id\x18\x01 \x01(\t\x12+\n\x05nodes\x18\x02 \x03(\x0b\x32\x1c.secretflow.pipeline.NodeDef\"B\n\tNodeState\x12\n\n\x02id\x18\x01 \x01(\t\x12)\n\x05state\x18\x02 \x01(\x0e\x32\x1a.secretflow.pipeline.State\"u\n\rPipelineState\x12\n\n\x02id\x18\x01 \x01(\t\x12)\n\x05state\x18\x02 \x01(\x0e\x32\x1a.secretflow.pipeline.State\x12-\n\x05nodes\x18\x03 \x03(\x0b\x32\x1e.secretflow.pipeline.NodeState*K\n\x05State\x12\x0b\n\x07Staging\x10\x00\x12\x0f\n\x0bInitialized\x10\x01\x12\x0b\n\x07Running\x10\x02\x12\x0b\n\x07Succeed\x10\x03\x12\n\n\x06\x46\x61iled\x10\x04\x62\x06proto3'
  ,
  dependencies=[secretflow_dot_protos_dot_component_dot_comp__pb2.DESCRIPTOR,])

_STATE = _descriptor.EnumDescriptor(
  name='State',
  full_name='secretflow.pipeline.State',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='Staging', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='Initialized', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='Running', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='Succeed', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='Failed', index=4, number=4,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=537,
  serialized_end=612,
)
_sym_db.RegisterEnumDescriptor(_STATE)

State = enum_type_wrapper.EnumTypeWrapper(_STATE)
Staging = 0
Initialized = 1
Running = 2
Succeed = 3
Failed = 4



_NODEDEF = _descriptor.Descriptor(
  name='NodeDef',
  full_name='secretflow.pipeline.NodeDef',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='secretflow.pipeline.NodeDef.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='domain', full_name='secretflow.pipeline.NodeDef.domain', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='name', full_name='secretflow.pipeline.NodeDef.name', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='version', full_name='secretflow.pipeline.NodeDef.version', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='attr_paths', full_name='secretflow.pipeline.NodeDef.attr_paths', index=4,
      number=5, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='attrs', full_name='secretflow.pipeline.NodeDef.attrs', index=5,
      number=6, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='inputs', full_name='secretflow.pipeline.NodeDef.inputs', index=6,
      number=7, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='outputs', full_name='secretflow.pipeline.NodeDef.outputs', index=7,
      number=8, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=107,
  serialized_end=276,
)


_PIPELINEDEF = _descriptor.Descriptor(
  name='PipelineDef',
  full_name='secretflow.pipeline.PipelineDef',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='secretflow.pipeline.PipelineDef.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='nodes', full_name='secretflow.pipeline.PipelineDef.nodes', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=278,
  serialized_end=348,
)


_NODESTATE = _descriptor.Descriptor(
  name='NodeState',
  full_name='secretflow.pipeline.NodeState',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='secretflow.pipeline.NodeState.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='state', full_name='secretflow.pipeline.NodeState.state', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=350,
  serialized_end=416,
)


_PIPELINESTATE = _descriptor.Descriptor(
  name='PipelineState',
  full_name='secretflow.pipeline.PipelineState',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='secretflow.pipeline.PipelineState.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='state', full_name='secretflow.pipeline.PipelineState.state', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='nodes', full_name='secretflow.pipeline.PipelineState.nodes', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=418,
  serialized_end=535,
)

_NODEDEF.fields_by_name['attrs'].message_type = secretflow_dot_protos_dot_component_dot_comp__pb2._ATTRIBUTE
_PIPELINEDEF.fields_by_name['nodes'].message_type = _NODEDEF
_NODESTATE.fields_by_name['state'].enum_type = _STATE
_PIPELINESTATE.fields_by_name['state'].enum_type = _STATE
_PIPELINESTATE.fields_by_name['nodes'].message_type = _NODESTATE
DESCRIPTOR.message_types_by_name['NodeDef'] = _NODEDEF
DESCRIPTOR.message_types_by_name['PipelineDef'] = _PIPELINEDEF
DESCRIPTOR.message_types_by_name['NodeState'] = _NODESTATE
DESCRIPTOR.message_types_by_name['PipelineState'] = _PIPELINESTATE
DESCRIPTOR.enum_types_by_name['State'] = _STATE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

NodeDef = _reflection.GeneratedProtocolMessageType('NodeDef', (_message.Message,), {
  'DESCRIPTOR' : _NODEDEF,
  '__module__' : 'secretflow.protos.pipeline.pipeline_pb2'
  # @@protoc_insertion_point(class_scope:secretflow.pipeline.NodeDef)
  })
_sym_db.RegisterMessage(NodeDef)

PipelineDef = _reflection.GeneratedProtocolMessageType('PipelineDef', (_message.Message,), {
  'DESCRIPTOR' : _PIPELINEDEF,
  '__module__' : 'secretflow.protos.pipeline.pipeline_pb2'
  # @@protoc_insertion_point(class_scope:secretflow.pipeline.PipelineDef)
  })
_sym_db.RegisterMessage(PipelineDef)

NodeState = _reflection.GeneratedProtocolMessageType('NodeState', (_message.Message,), {
  'DESCRIPTOR' : _NODESTATE,
  '__module__' : 'secretflow.protos.pipeline.pipeline_pb2'
  # @@protoc_insertion_point(class_scope:secretflow.pipeline.NodeState)
  })
_sym_db.RegisterMessage(NodeState)

PipelineState = _reflection.GeneratedProtocolMessageType('PipelineState', (_message.Message,), {
  'DESCRIPTOR' : _PIPELINESTATE,
  '__module__' : 'secretflow.protos.pipeline.pipeline_pb2'
  # @@protoc_insertion_point(class_scope:secretflow.pipeline.PipelineState)
  })
_sym_db.RegisterMessage(PipelineState)


# @@protoc_insertion_point(module_scope)
